### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by sopertob** [nylki/pen-paper-coffee-syntax#20]
When the pen-paper-coffee-syntax theme is running, headers won't soft wrap. Instead, they run off the edge of the screen.

**Comment by nylki** [comment]
I am aware of that issue and it annoys me aswell.


**Screenshot of the issue:**
![bildschirmfoto 2015-07-22 um 15 07 54](https://cloud.githubusercontent.com/assets/1710598/8826028/b7fdac62-3083-11e5-89f3-498fff35280f.png)

**how it looks like with no changes to `font-size` in the syntax-theme (One-Light)**:
![how it looks like with no changes to `font-size` in the syntax-theme (One-Light)](https://cloud.githubusercontent.com/assets/1710598/8826031/be2cd8ba-3083-11e5-8351-25bda5997b38.png)




The problem lies in the fixed with of Atoms absolute positioned lines.
Each line of text in Atom has its own `div class="line"` which contains divs with classes used for styling specific syntax features.

When a line wraps is determined by its width. Example of a line with a markdown header:
```.html
<div class="line" style="position: absolute; top: 0px; width: 550px;" data-screen-row="108">
   <span class="source gfm">
       <span class="markup heading heading-2 gfm">
           <span class="markup heading marker gfm">##</span>
           <span class="markup heading space gfm"> </span>
           Very very long header, that flows over in the current version off 
       </span>
     </span>
</div>
```

If I just do a `word-wrap` inside any of those spans on eg. `.gfm .heading` the result would be even worse, as the `<span class="markup heading heading-2 gfm">` would wrap in itelf (that is, inside the line) and its impossible to control.

The problem I think (which I can't confirm right now) lies in the wrapping/linelength being determined by the font-size set via your settings. So when manipulation the `font-size` in the syntax theme, the calculation of the propper wrapping or line-length by atom doesn't properly work for those lines anymore.

I guess, if it was possible to select the `.line` that contains a `.heading` you could set a `max-width` to earlier wrap the text. As there is no *parent selector* in css, this is at the moment not possible. But even if that would be possible I am not quite sure if it would work out properly as it might break the structure of the document.


Of course, if anybody has a different view on the situation I am eager to hear it. Maybe I am just overseeing a detail. /cc @braver @jesseweed @kevinsawicki

**Comment by sbaack** [comment]
Not really a solution, but could you include an option to not change the font size as a workaround? I really like the theme, but issues with the headers prevent me from using it :-(

**Comment by nylki** [comment]
@sbaack It got even worse with cursor positioning etc. :/

I am pushinh an update disabling the fontsize changes until the issues are fixed (possibly in Atom itself). I can't really add an option as syntax-themes don't expose options.

**Comment by nylki** [comment]
this issue is most likely relevant: https://github.com/atom/atom/issues/6055

**Comment by sbaack** [comment]
Thanks! I hope the issues in Atom will get fixed in the not-so-distant future. Unfortunately I now have a new issue with footnotes which I think is related to the change: Sometimes (but not always) the font-size is not only reduced for the footnote itself but also for the text that comes after it (for the rest of the line).

**Comment by nylki** [comment]
@sbaack Ahh, about the newly styled footnotes. I suppose you are also using the pfm/pandoc-flavoured-markdown package? 
Do you have an example at hand where that issues is visible? :)

**Comment by sbaack** [comment]
Good that you mention the pfm package, there seems to problem:
<img width="628" alt="screen shot 2015-10-02 at 1 28 24 am" src="https://cloud.githubusercontent.com/assets/8274140/10236378/0b1d895e-68a5-11e5-9ba9-b7e2bc981054.png">

**Comment by nylki** [comment]
@sbaack I linked your image in an issue at *pfm*. Let's see if somebody got a solution to that! Hope it's not too much of an issue to you right now. Otherwise you can edit your local copy of the theme and edit/comment out the `.pfm .footnote` section, so that no styling is applied to footnotes.

**Comment by sbaack** [comment]
I will comment out the section for now then. Thanks again for your help and for the great theme :-)

**Comment by nylki** [comment]
@sbaack You are welcome! Glad you like it even though it has some problems because if experimental stylings ;)

I suppose I'll actually comment the section out in the *master* if there is no quick fix. I prefer to not have style breaking features in the theme.

**Comment by the-solipsist** [comment]
The base issues https://github.com/atom/atom/issues/6055 and https://github.com/atom/atom/pull/7945 seem to be fixed, so any chance that we will have header-resizing again?

**Comment by nylki** [comment]
@the-solipsist Unfortunately, there still are issues with bigger than 1em/100% fontsizes.
![ppc_fontsize](https://cloud.githubusercontent.com/assets/1710598/13176013/130aad3a-d70f-11e5-98d0-dfcb00834085.png)

**Comment by the-solipsist** [comment]
Are there any other external blockers to this being solved?  If so, should one of us open up an issue report with [Atom](https://github.com/atom/atom/issues/)?

**Comment by nylki** [comment]
@the-solipsist I just created a meta-issue at atom-core (see above). I am not sure if other work is currently underway to overcome those rendering issues.

**Comment by nylki** [comment]
closed as wontfix.
