### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by sopertob** [nylki/pen-paper-coffee-syntax#25]
Is it possible to change the style to highlight inline footnotes? So that `Here is a point.[^And a supporting footnote.]` (or the `^[` pandoc variation) would highlight the footnote text to make it distinct from the body?

**Comment by sopertob** [comment]
I found this in markdown.less and changed "light ink" to "orange." It works with the pandoc footnote variation but not the multimarkdown one.

`&.footnote, &.link, &.auto {
                &.destination {
                    .uri {
                        // Same as general .underline for markups
                        text-decoration: none;
                        border-bottom: @invisible-ink;
                        border-width: 0px 0px 1px 0px;
                        border-style: none none solid none;
                    }
                }

                // for now disabled as it is not reliable yet
                // position: relative;
                // top: -0.5em;
                // font-size: 85%;
                // font-weight:900;
                // so far comes from language-pfm

                // would be better?
                // font-style: normal;
                // vertical-align: super;
                // font-size: 85%;
                color:@orange;
            }`

**Comment by nylki** [comment]
Hey @sopertob!
Not sure if I understand correctly what you would like to have styled.
If you install [language-pfm (pandoc flavoured markdown](https://atom.io/packages/language-pfm), the footnotes should be styled individually, as seen in the screenshots.

In the end, a syntax theme can only style what a specific grammar/language package (*language-gfm*, *language-pfm*, language-markdown) captures.
To see the captured scopes you can enable dev-tools in Atom (view->toggle development tools), and the use the element inspector to see wether individual parts of a citation eg. are actually captured. If that is so, they can be styled with CSS, otherwise not.

Does that make sense to you? :) Or am I missing our point?

**Comment by sopertob** [comment]
This answers it some. I was looking to highlight (or change the background
to inline footnote text) in order to distinguish it from the body text. Pen
Paper Coffee style made footnotes a "light ink," I think, which was hard to
see as distinct from the regular text (in black). I changed the text to
orange in the *.less section I pasted in my initial query. I'm (trying) to
post an image of what I mean.[image: Inline image 1]
