### ISSUE TITLE
Style Project Find results heading pane

### ISSUE THREAD

**Issue by r0ckarong** [nylki/pen-paper-coffee-syntax#29]
Hi, 

your syntax theme uses a default color value for the Project Find heading pane and makes it impossible to use because it's dark text on dark background. 

If I add this to my styles.less it works fine:

```
.preview-pane .panel-heading {
  background-color: #e0dad3;
}
```

I don't understand Atom theming very much but if you tell me where I need to apply this and how I'll create a pull request. The color is the same as in @heftstreifen (toller Name!) in the colors.less

![screen shot 2016-09-26 at 13 51 29](https://cloud.githubusercontent.com/assets/4920542/18834086/5c44feaa-83f4-11e6-985c-e203c5ef7d21.png)

![screen_shot_2016-09-26_at_14_20_51](https://cloud.githubusercontent.com/assets/4920542/18834119/845e0f4e-83f4-11e6-9521-a424aef3f3d3.png)

**Comment by nylki** [comment]
Hi @r0ckarong,
Thanks for your report! However, I can't reproduce it.
I did a quick screnrecording, see: https://vimeo.com/184362115 (pw: penpapercoffe)

Are you sure it isn't any other package that might interfer with the colors?

What UI-theme do you use? What happens if you choose a different UI-Theme or a different Syntax-Theme, does the behaviour remain?

**Comment by r0ckarong** [comment]
You're right. I thought I checked thoroughly. This comes from the Atom Material theme. Will file it there.

Danke trotzdem für das tolle Theme!

**Comment by nylki** [comment]
> Danke trotzdem für das tolle Theme!

Gerne :)
